export enum Color{
    AQUA, BEIGE, BLACK, BLUE, BROWN, CHOCOLATE, CORAL, CYAN, DARKBLUE, DARKGRAY, DARKGREEN, DARKMAGENTA, DARKORANGE, DARKRED, DARKSEAGREEN, FUCHSIA, GOLD,
     GREY, GREEN, INDIGO, IVORY, KHAKI, LAVENDER, LIGHTBLUE, LIGHTGREY, LIGHTGREEN, LIGHTPINK, LIME, LIMEGREEN, LINEN, MAGENTA, NAVY, OLIVE,  ORANGE, PINK,
    PURPLE, RED, ROYALBLUE, SALMON, SILVER, TURQUOISE, VIOLET, WHITE, YELLOW
}